Repository decidim/decidim-initiatives, pull requests merged in 2018-03, with the labels that each got.

#115 Update decidim to 0.10-stable
  Gemfile
  Gemfile.lock
  app/views/decidim/initiatives/initiatives/_filters.html.erb
Labels: in-progress

#117 partially_translated_attribute replacement
  app/mailers/decidim/initiatives/initiatives_mailer.rb
  app/views/decidim/initiatives/initiatives_mailer/notify_creation.html.erb
  docker-compose.yml
Labels: in-progress

#118 Replacement of partially_translated_attribute by translated_attribute
  app/controllers/concerns/decidim/initiatives/admin/initiative_admin.rb
  app/controllers/decidim/initiatives/admin/features_controller.rb
  app/controllers/decidim/initiatives/admin/initiatives_controller.rb
  app/controllers/decidim/initiatives/committee_requests_controller.rb
  app/controllers/decidim/initiatives/create_initiative_controller.rb
  app/controllers/decidim/initiatives/initiatives_controller.rb
  app/helpers/decidim/initiatives/partial_translations_helper.rb
  app/models/decidim/initiatives_vote.rb
  app/views/decidim/initiatives/_initiative.html.erb
  app/views/decidim/initiatives/admin/initiatives/index.html.erb
  app/views/decidim/initiatives/admin/initiatives/show.html.erb
  app/views/decidim/initiatives/committee_requests/new.html.erb
  app/views/decidim/initiatives/initiatives/show.html.erb
  app/views/layouts/decidim/_initiative_header.html.erb
  lib/decidim/initiatives/participatory_space.rb
  spec/controllers/decidim/initiatives/committee_requests_controller_spec.rb
  spec/system/committee_request_spec.rb
Labels: in-progress

#116 Log actions on initiatives
  Gemfile.lock
  app/commands/decidim/initiatives/admin/publish_initiative.rb
  app/commands/decidim/initiatives/admin/send_initiative_to_technical_validation.rb
  app/commands/decidim/initiatives/admin/unpublish_initiative.rb
  app/commands/decidim/initiatives/admin/update_initiative.rb
  app/controllers/decidim/initiatives/admin/initiatives_controller.rb
  app/models/decidim/initiative.rb
  app/presenters/decidim/initiatives/admin_log/initiative_presenter.rb
  config/locales/en.yml
  decidim-initiatives.gemspec
  spec/commands/decidim/initiatives/admin/publish_initiative_spec.rb
  spec/commands/decidim/initiatives/admin/send_initiative_to_technical_validation_spec.rb
  spec/commands/decidim/initiatives/admin/unpublish_initiative_spec.rb
  spec/commands/decidim/initiatives/create_initiative_spec.rb
  spec/models/decidim/initiative_spec.rb
  spec/shared/update_initiative_example.rb
Labels: in-progress, status: WIP

#120 Fixed issue when creating scopes for an initiative type
  app/views/decidim/initiatives/admin/initiatives_type_scopes/_form.html.erb
  spec/commands/decidim/initiatives/admin/create_initiative_type_scope_spec.rb
  spec/commands/decidim/initiatives/admin/create_initiative_type_spec.rb
  spec/commands/decidim/initiatives/admin/update_initiative_spec.rb
  spec/system/admin/initiative_types_controller_spec.rb
  spec/system/admin/initiatives_type_scopes_controller_spec.rb
  spec/system/committee_request_spec.rb
Labels: in-progress

#122 New Crowdin translations
  ca/config/locales/ca.yml
  es-ES/config/locales/es.yml
  eu/config/locales/eu.yml
  fi/config/locales/fi.yml
  fr/config/locales/fr.yml
  gl/config/locales/gl.yml
  it/config/locales/it.yml
  nl/config/locales/nl.yml
  pl/config/locales/pl.yml
  pt-BR/config/locales/pt.yml
  pt-PT/config/locales/pt.yml
  ru-UA/config/locales/ru.yml
  ru/config/locales/ru.yml
  sv-SE/config/locales/sv.yml
Labels: status: WIP

#123 Fixes #109 - random test failure
  ca/config/locales/ca.yml
  es-ES/config/locales/es.yml
  eu/config/locales/eu.yml
  fi/config/locales/fi.yml
  fr/config/locales/fr.yml
  gl/config/locales/gl.yml
  it/config/locales/it.yml
  nl/config/locales/nl.yml
  pl/config/locales/pl.yml
  pt-BR/config/locales/pt.yml
  pt-PT/config/locales/pt.yml
  ru-UA/config/locales/ru.yml
  ru/config/locales/ru.yml
  spec/models/decidim/initiatives/abilities/current_user_ability_spec.rb
  spec/models/decidim/initiatives/abilities/vote_ability_spec.rb
  spec/system/committee_request_spec.rb
Labels: status: WIP
